name: cd pipeline
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update package index and install dependencies
            sudo apt-get update -y
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            
            # Install Docker
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update -y
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose

            # Add user to Docker group
            sudo usermod -aG docker $USER
            sudo chmod 666 /var/run/docker.sock  # Grant access to Docker socket

            # Navigate to the project directory and deploy
            echo "🔑 Navigating to project directory..."
            cd /home/ubuntu/
            if [ ! -d "fastapi-book-project" ]; then
              echo "🔑 Cloning repository..."
              git clone https://github.com/oyerohabib/fastapi-book-project.git
            fi
            cd fastapi-book-project
            git pull

            # Restart Docker & Deploy Containers
            echo "🔑 Restarting Docker..."
            sudo systemctl restart docker

            echo "🔑 Stopping any running containers..."
            docker-compose down  # Stop any running containers
            echo "🔑 Starting new containers..."
            docker-compose up -d --build

            # Restart nginx after containers are fully up
            echo "🔑 Restarting nginx..."
            sleep 5  # Ensure containers are fully up
            sudo systemctl restart nginx

            # Check Logs
            echo "🔑 Checking logs..."
            docker ps -a  # See if anything crashed
            docker logs fastapi-app  # Check FastAPI logs
            docker logs fastapi-nginx  # Check nginx logs
